<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H63L4E2" ignored="0" name="Test" tests="9" failures="2" timestamp="2022-06-07T01:37:21 PDT" time="0.237" errors="0">
  <testcase name="gmail" time="0.028" classname="com.testng.Retry_Demo">
    <skipped/>
  </testcase> <!-- gmail -->
  <testcase name="gmail" time="0.004" classname="com.testng.Retry_Demo">
    <skipped/>
  </testcase> <!-- gmail -->
  <testcase name="gmail" time="0.003" classname="com.testng.Retry_Demo">
    <skipped/>
  </testcase> <!-- gmail -->
  <testcase name="gmail" time="0.004" classname="com.testng.Retry_Demo">
    <failure type="java.lang.AssertionError" message="expected [Vimala@gmail.com] but found [Vimala@yahoo.com]">
      <![CDATA[java.lang.AssertionError: expected [Vimala@gmail.com] but found [Vimala@yahoo.com]
at com.testng.Retry_Demo.gmail(Retry_Demo.java:52)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- gmail -->
  <testcase name="password" time="0.003" classname="com.testng.Retry_Demo">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.003" classname="com.testng.Retry_Demo">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.002" classname="com.testng.Retry_Demo">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.003" classname="com.testng.Retry_Demo">
    <failure type="java.lang.AssertionError" message="expected [456] but found [123]">
      <![CDATA[java.lang.AssertionError: expected [456] but found [123]
at com.testng.Retry_Demo.password(Retry_Demo.java:40)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- password -->
  <testcase name="username" time="0.004" classname="com.testng.Retry_Demo"/>
</testsuite> <!-- Test -->
